### ISSUE TITLE
Bug: Changes are not saved to existDB

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#165]
@wsalesky When changes are made to records and we want to save them, we use the "Submit to Github" button. 
This morning we noticed that so far, there seems only to be a one-way road leading from manuForma to GitHub: when we close the record in manuForma and later re-open it, the changes are not visible.

What we implicitly expect when we use the "Submit to Github" button is that the changes are also saved to the local existDB, so that the changes will also be visible the next time we open the record in manuForma.

**Comment by wsalesky** [comment]
@mMoliere Interesting. This is supposed to be handled by the webhooks, but I will make it also save directly to the db, in case the webhooks fail. Is the saving to github working correctly?

**Comment by mMoliere** [comment]
@wsalesky Yes, on the Github side it works as expected. When we use the "Submit to Github" button, a pull request it created and we can see the changed file.

**Comment by wsalesky** [comment]
@mMoliere when you merge the pull request it is supposed to save to the database. It sounds like that is not happening? I will build in the direct save as a backup, but also I would like to investigate the webhook issue. Can you tell me what was your last data merge, so I can look at the webhooks?

**Comment by mMoliere** [comment]
@wsalesky I can definitively say that the file submitted to Github is not saved in the database – I checked in Exide. 

The last file I merged was https://github.com/majlis-erc/majlis-data/blob/main/data/manuscripts/tei/2.xml

**Comment by wsalesky** [comment]
@mMoliere Okay. I will take a look at both ends of this issue. Should have a solution running by the end of the day.

**Comment by mMoliere** [comment]
@wsalesky Awesome!

**Comment by wsalesky** [comment]
@mMoliere ready for testing. Let me know if there are any issues. If not, please close this issue.

**Comment by mMoliere** [comment]
@wsalesky Now, the following message is displayed when I push the "Submit to Github" button:
![Screenshot 2023-07-06 at 17 20 28](https://github.com/majlis-erc/manuForma/assets/73166992/b9f9849b-9293-44d4-85a7-a49add036ecf)

I checked the webhook. It looks fine

**Comment by wsalesky** [comment]
@mMoliere I think this is fixed. Please delete my recent pull request, it was just a test record.

**Comment by mMoliere** [comment]
@wsalesky Sorry to reopen this issue. But the app does not open now. Instead an error message is shown. I don't know if it is related to your work. I have worked on tweaks to the collapsibles, but I would not expext that they could cause an error like this:

```
<h2>HTTP ERROR 500 javax.servlet.ServletException: 
javax.servlet.ServletException: An error occurred while processing 
request to /exist/apps/manuForma/: err:XQST0059 error found while 
loading module config: Error while loading module modules/config.xqm: 
namespace URI declared by module 
(http://localhost:8080/manuForma/config) does not match namespace URI in
 import statement, which was: http://localhost/manuForma/config</h2>


URI: | /exist/apps/manuForma/
-- | --
500
javax.servlet.ServletException:  javax.servlet.ServletException: An error occurred while processing  request to /exist/apps/manuForma/: err:XQST0059 error found while  loading module config: Error while loading module modules/config.xqm:  namespace URI declared by module  (http://localhost:8080/manuForma/config) does not match namespace URI in  import statement, which was: http://localhost/manuForma/config
XQueryURLRewrite
javax.servlet.ServletException:  javax.servlet.ServletException: An error occurred while processing  request to /exist/apps/manuForma/: err:XQST0059 error found while  loading module config: Error while loading module modules/config.xqm:  namespace URI declared by module  (http://localhost:8080/manuForma/config) does not match namespace URI in  import statement, which was: http://localhost/manuForma/config
javax.servlet.ServletException: An error  occurred while processing request to /exist/apps/manuForma/:  err:XQST0059 error found while loading module config: Error while  loading module modules/config.xqm: namespace URI declared by module  (http://localhost:8080/manuForma/config) does not match namespace URI in  import statement, which was: http://localhost/manuForma/config
org.exist.xquery.XPathException: err:XQST0059  error found while loading module config: Error while loading module  modules/config.xqm: namespace URI declared by module  (http://localhost:8080/manuForma/config) does not match namespace URI in  import statement, which was: http://localhost/manuForma/config


<h3>Caused by:</h3><pre>javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/manuForma/: err:XQST0059 error found while loading module config: Error while loading module modules/config.xqm: namespace URI declared by module (http://localhost:8080/manuForma/config) does not match namespace URI in import statement, which was: http://localhost/manuForma/config
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/manuForma/: err:XQST0059 error found while loading module config: Error while loading module modules/config.xqm: namespace URI declared by module (http://localhost:8080/manuForma/config) does not match namespace URI in import statement, which was: http://localhost/manuForma/config
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:366)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 18 more
Caused by: org.exist.xquery.XPathException: err:XQST0059 error found while loading module config: Error while loading module modules/config.xqm: namespace URI declared by module (http://localhost:8080/manuForma/config) does not match namespace URI in import statement, which was: http://localhost/manuForma/config
	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2667)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2599)
	at org.exist.xquery.XQueryContext.importModuleFromLocation(XQueryContext.java:2528)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2462)
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6276)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5291)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:3991)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3936)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3591)
	at org.exist.xquery.XQuery.compile(XQuery.java:238)
	at org.exist.xquery.XQuery.compile(XQuery.java:175)
	at org.exist.xquery.XQuery.compile(XQuery.java:133)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:239)
	... 41 more
</pre>
```

**Comment by wsalesky** [comment]
Hum, I will take a look

**Comment by wsalesky** [comment]
@mMoliere can you try it now?

**Comment by mMoliere** [comment]
@wsalesky Yes, that worked!
